name: linux build

on: push

jobs:
  build:
    name: Compile
    runs-on: ubuntu
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run build
        run: |
          make && make -f Makefile.libretro
          file gong.so
          file gong_libretro.so

      - name: Build folder
        run: |
          mkdir -p build && cd build && 
          cp ../gong.so gong-linux-`uname -m`.so && 
          cp ../gong_libretro.dylib gong_libretro-linux-`uname -m`.so

      - uses: actions/upload-artifact@v4
        with:
          name: linux
          path: |
            build/*
