name: mac build

on:
  push

jobs:
  build:
    name: Compile
    runs-on: macos-12
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run build
        run: |
          make && make -F Makefile.libretro
          file gong.so
          file gong_libretro.dylib