name: linux build

on:
  push

jobs:
  build:
    name: Compile
    runs-on: ubuntu
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run build
        run: |
          make && make -f Makefile.libretro
          file gong.so
          ls *